import React, { useState } from 'react';
import { generateBusinessStrategy } from '../services/geminiService';
import { LoadingState } from '../types';
import { Sparkles, Loader2, Send, MapPin, Target, Command, ArrowUpRight } from 'lucide-react';
import ReactMarkdown from 'react-markdown';

const NICHES = [
  "Wedding Celebrant", "Funeral Celebrant", "Baby Naming", "Vow Renewal", 
  "Elopement", "Spiritual", "Pet Memorial", "Corporate Host"
];

export const AIStrategist: React.FC = () => {
  const [niche, setNiche] = useState(NICHES[0]);
  const [location, setLocation] = useState('');
  const [struggle, setStruggle] = useState('');
  const [status, setStatus] = useState<LoadingState>(LoadingState.IDLE);
  const [result, setResult] = useState('');

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!location || !struggle) return;

    setStatus(LoadingState.LOADING);
    try {
      const strategy = await generateBusinessStrategy(niche, location, struggle);
      setResult(strategy);
      setStatus(LoadingState.SUCCESS);
    } catch (error) {
      setResult("We encountered an issue connecting to our strategy engine. Please try again later.");
      setStatus(LoadingState.ERROR);
    }
  };

  return (
    <div className="dark-glass rounded-none border border-charcoal-800 overflow-hidden flex flex-col lg:flex-row shadow-2xl shadow-black/20">
      {/* Input Side */}
      <div className="p-8 md:p-16 lg:w-[45%] bg-charcoal-900 relative">
        <div className="absolute top-0 right-0 p-4 opacity-10">
          <Command size={120} strokeWidth={0.5} className="text-white" />
        </div>
        
        <div className="mb-12 relative z-10">
          <div className="flex items-center gap-2 text-clay-400 mb-4">
            <span className="w-2 h-2 bg-clay-500 rounded-full animate-pulse"></span>
            <span className="font-mono uppercase tracking-widest text-[10px] font-bold">AI Strategy Console</span>
          </div>
          <h2 className="text-4xl md:text-5xl font-serif text-cream-50 mb-6 leading-tight">
            Consult the <span className="text-clay-400 italic">Oracle</span>
          </h2>
          <p className="text-stone-400 font-light leading-relaxed">
            Provide your details below to receive a bespoke, market-dominating roadmap generated by our specialized AI strategist.
          </p>
        </div>

        <form onSubmit={handleSubmit} className="space-y-8 relative z-10">
          <div className="group">
            <label className="block text-stone-500 text-[10px] font-mono font-bold uppercase tracking-widest mb-3 group-focus-within:text-clay-400 transition-colors">Specialization</label>
            <select 
              value={niche} 
              onChange={(e) => setNiche(e.target.value)}
              className="w-full bg-charcoal-800/50 border-b border-stone-700 rounded-none px-0 py-4 text-xl text-white focus:outline-none focus:border-clay-400 focus:bg-charcoal-800 transition-all appearance-none cursor-pointer font-serif"
            >
              {NICHES.map(n => <option key={n} value={n} className="bg-charcoal-900">{n}</option>)}
            </select>
          </div>

          <div className="group">
            <label className="block text-stone-500 text-[10px] font-mono font-bold uppercase tracking-widest mb-3 group-focus-within:text-clay-400 transition-colors">Target Market</label>
            <input 
              type="text"
              placeholder="e.g. Melbourne, Australia"
              value={location}
              onChange={(e) => setLocation(e.target.value)}
              className="w-full bg-charcoal-800/50 border-b border-stone-700 rounded-none px-0 py-4 text-xl text-white focus:outline-none focus:border-clay-400 focus:bg-charcoal-800 transition-all placeholder-stone-700 font-serif"
              required
            />
          </div>

          <div className="group">
            <label className="block text-stone-500 text-[10px] font-mono font-bold uppercase tracking-widest mb-3 group-focus-within:text-clay-400 transition-colors">Primary Objective</label>
            <input 
              type="text"
              placeholder="e.g. Booking premium elopements"
              value={struggle}
              onChange={(e) => setStruggle(e.target.value)}
              className="w-full bg-charcoal-800/50 border-b border-stone-700 rounded-none px-0 py-4 text-xl text-white focus:outline-none focus:border-clay-400 focus:bg-charcoal-800 transition-all placeholder-stone-700 font-serif"
              required
            />
          </div>

          <button 
            type="submit" 
            disabled={status === LoadingState.LOADING}
            className="w-full mt-8 bg-clay-500 hover:bg-clay-400 text-white font-mono font-bold py-5 px-8 tracking-widest uppercase text-[10px] transition-all flex items-center justify-between group disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {status === LoadingState.LOADING ? (
              <span className="flex items-center gap-3"><Loader2 className="animate-spin" size={16} /> Processing Data</span>
            ) : (
              <span className="flex items-center gap-3">Initialize Strategy</span>
            )}
            <Send size={16} className="group-hover:translate-x-1 transition-transform" />
          </button>
        </form>
      </div>

      {/* Output Side */}
      <div className="p-8 md:p-16 lg:w-[55%] bg-charcoal-950/50 border-l border-white/5 overflow-y-auto max-h-[800px] custom-scrollbar">
        {status === LoadingState.IDLE && (
          <div className="h-full flex flex-col items-center justify-center text-center opacity-30 select-none">
            <Sparkles size={80} strokeWidth={0.5} className="text-white mb-6" />
            <p className="font-serif text-3xl text-white">Awaiting Input</p>
          </div>
        )}

        {status === LoadingState.LOADING && (
          <div className="h-full flex flex-col items-center justify-center text-center space-y-8">
            <div className="relative">
               <div className="w-24 h-24 border-t-2 border-clay-500 rounded-full animate-spin"></div>
               <div className="absolute inset-0 flex items-center justify-center">
                 <div className="w-16 h-16 border-b-2 border-white/20 rounded-full animate-spin [animation-duration:3s]"></div>
               </div>
            </div>
            <div className="space-y-2">
              <p className="text-white font-serif text-xl animate-pulse">Consulting Knowledge Base...</p>
              <p className="text-stone-600 font-mono text-[10px] uppercase tracking-widest">Analyzing {niche} trends in {location}</p>
            </div>
          </div>
        )}

        {status === LoadingState.SUCCESS && (
          <div className="animate-fade-in">
             <div className="flex items-center justify-between mb-8 pb-8 border-b border-white/10">
               <div>
                 <h3 className="font-serif text-3xl text-white mb-2">Strategic Dossier</h3>
                 <p className="text-[10px] font-mono uppercase tracking-widest text-clay-400">Generated for {niche}</p>
               </div>
               <div className="p-3 border border-white/10 rounded-full">
                 <Sparkles size={20} className="text-clay-400" />
               </div>
             </div>
             
             <div className="prose prose-invert prose-lg max-w-none
               prose-headings:font-serif prose-headings:font-normal prose-headings:text-cream-100
               prose-p:text-stone-400 prose-p:font-light prose-p:leading-relaxed
               prose-li:text-stone-300
               prose-strong:text-clay-300 prose-strong:font-normal
               prose-a:text-clay-400 hover:prose-a:text-clay-300">
               <ReactMarkdown>{result}</ReactMarkdown>
             </div>
             
             <div className="mt-12 pt-8 border-t border-white/10 flex justify-end">
               <button className="text-[10px] font-mono font-bold uppercase tracking-widest text-stone-500 hover:text-white transition-colors flex items-center gap-2">
                 Download PDF Report <ArrowUpRight size={14} />
               </button>
             </div>
          </div>
        )}
      </div>
    </div>
  );
};